#!/bin/sh

xrdb ~/.Xresources

# keyboard repeat rate
xset r rate 250 25 &

# bind escape to capslock
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape' &

# background
feh --bg-scale ~/.dwm/wallpaper.jpeg &

